version: "3.4"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  jaeger:
    container_name: "tracing.jaeger.agent"
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - jaeger-demo
    labels:
      NAME: "jaeger-agent"

  discovery-service:
    container_name: discovery-service
    image: batmansl/discovery-service:latest
    ports:
      - "8700:8700"
    volumes:
      - /tmp:/workspace/logs

  admin-service:
    container_name: admin-service
    image: batmansl/admin-service:latest
    ports:
      - "9003:9003"
    links:
      - discovery-server:discovery-server
    environment:
      - EUREKA_URI=http://discovery-server:8761/eureka
    volumes:
      - /tmp:/workspace/logs

  consumer-service:
    container_name: consumer-service
    image: batmansl/consumer-service:latest
    ports:
      - "9002:9002"
    links:
      - discovery-server:discovery-server
    environment:
      - EUREKA_URI=http://discovery-server:8761/eureka
    volumes:
      - /tmp:/workspace/logs

  order-service:
    container_name: order-service
    image: batmansl/order-service:latest
    ports:
      - "9001:9001"
    links:
      - discovery-server:discovery-server
    environment:
      - EUREKA_URI=http://discovery-server:8761/eureka
    volumes:
      - /tmp:/workspace/logs

  worker-service:
    container_name: worker-service
    image: batmansl/worker-service:latest
    ports:
      - "9004:9004"
    links:
      - discovery-server:discovery-server
    environment:
      - EUREKA_URI=http://discovery-server:8761/eureka
    volumes:
      - /tmp:/workspace/logs

  utility-service:
    container_name: utility-service
    image: batmansl/utility-service:latest
    ports:
      - "9000:9000"
    links:
      - discovery-server:discovery-server
    environment:
      - EUREKA_URI=http://discovery-server:8761/eureka
    volumes:
      - /tmp:/workspace/logs

  api-gateway:
    container_name: api-gateway
    image: batmansl/gateway:latest
    ports:
      - "9100:9100"
    links:
      - discovery-server:discovery-server
    environment:
      - EUREKA_URI=http://discovery-server:8761/eureka
    volumes:
      - /tmp:/workspace/logs
